Repository hawks-atlanta/frontend-react, pull requests merged in 2023-10, with the labels that each got.

#28 chore: Create docker-compose
  .github/workflows/testing.yaml
  docker-compose.yaml
Labels: cd, ci

#30 ci: Remove component testing
  .github/workflows/coverage.yaml
  .github/workflows/tagging.yaml
  .github/workflows/testing.yaml
  .nycrc
  .nycrc.json
  cypress.config.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/Button/Button.spec.cy.tsx
  tsconfig.json
  vite.config.ts
Labels: ci

#33 feat: Implementing login endpoint
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/context/.gitkeep
  src/context/AuthContext.tsx
  src/hooks/.gitkeep
  src/hooks/useLocalStorage.tsx
  src/hooks/useSession.tsx
  src/main.tsx
  src/screens/Login.tsx
  src/screens/middlewares/AuthMiddleware.tsx
  src/services/.gitkeep
  src/services/auth/login.service.ts
Labels: enhancement

#36 fix: Support environment variables
  .env.example
  .gitignore
  README.md
  src/config/environment.ts
  src/services/auth/login.service.ts
Labels: bug, cd

#34 feat: Register
  .github/workflows/coverage.yaml
  .github/workflows/testing.yaml
  cypress/e2e/auth/login.cy.ts
  cypress/e2e/auth/register.cy.ts
  cypress/e2e/auth/tests-data.ts
  cypress/e2e/register.cy.ts
  src/context/AuthContext.tsx
  src/hooks/useSession.tsx
  src/screens/Register.tsx
  src/services/auth/register.service.ts
Labels: feature

#37 release: v0.0.4
  .env.example
  .eslintrc.cjs
  .github/workflows/coverage.yaml
  .github/workflows/tagging.yaml
  .github/workflows/testing.yaml
  .gitignore
  .nycrc
  .nycrc.json
  CHANGELOG.md
  README.md
  cypress.config.ts
  cypress/e2e/auth/login.cy.ts
  cypress/e2e/auth/register.cy.ts
  cypress/e2e/auth/tests-data.ts
  cypress/e2e/home.cy.ts
  cypress/e2e/navbar.cy.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  docker-compose.yaml
  package-lock.json
  package.json
  pnpm-lock.yaml
  public/Logos/logo.png
  src/components/Button/Button.spec.cy.tsx
  src/components/Button/Button.tsx
  src/components/FeatureCard/FeatureCard.tsx
  src/components/Nav/Nav.tsx
  src/components/Nav/NavButton.tsx
  src/config/environment.ts
  src/context/.gitkeep
  src/context/AuthContext.tsx
  src/hooks/.gitkeep
  src/hooks/useLocalStorage.tsx
  src/hooks/useSession.tsx
  src/main.tsx
  src/screens/App.tsx
  src/screens/Login.tsx
  src/screens/Register.tsx
  src/screens/middlewares/AuthMiddleware.tsx
  src/services/.gitkeep
  src/services/auth/login.service.ts
  src/services/auth/register.service.ts
  tsconfig.json
  vite.config.ts
Labels: cd

#40 release: v0.0.7
  .dockerignore
  .github/workflows/release.yaml
  CHANGELOG.md
  Dockerfile
  package.json
  version.py
Labels: cd

#32 feat: #31_FilePage
  src/components/DropdownMenu/Dropdown.tsx
  src/components/FileElement/File.tsx
  src/components/Nav/Nav.tsx
  src/components/Sidebar/Sidebar.tsx
  src/main.tsx
  src/screens/FilePage.tsx
Labels: ui

#41 feat: Check if session is valid after recovering it
  .github/workflows/coverage.yaml
  .github/workflows/testing.yaml
  src/hooks/useSession.tsx
  src/services/auth/refresh.service.ts
Labels: feature

#55 fix(ui): Update navbar according to session
  src/components/Nav/Nav.tsx
Labels: bug, ui

#57 feat: List user files
  .github/workflows/testing.yaml
  docker-compose.yaml
  src/components/DropdownMenu/Dropdown.tsx
  src/components/FileElement/FileCard.tsx
  src/components/Sidebar/Sidebar.tsx
  src/screens/FilePage.tsx
  src/services/files/list-file.service.ts
  src/types/entities.ts
Labels: feature

#59 release: v0.0.11
  .github/workflows/coverage.yaml
  .github/workflows/testing.yaml
  CHANGELOG.md
  docker-compose.yaml
  package.json
  src/components/DropdownMenu/Dropdown.tsx
  src/components/FileElement/FileCard.tsx
  src/components/Nav/Nav.tsx
  src/components/Sidebar/Sidebar.tsx
  src/hooks/useSession.tsx
  src/main.tsx
  src/screens/FilePage.tsx
  src/services/auth/refresh.service.ts
  src/services/files/list-file.service.ts
  src/types/entities.ts
Labels: cd

#58 feat: Create folders
  cypress/e2e/auth/login.cy.ts
  cypress/e2e/auth/register.cy.ts
  cypress/e2e/auth/tests-data.ts
  cypress/e2e/files/create-folder.cy.ts
  package.json
  pnpm-lock.yaml
  src/components/FileElement/FileCard.tsx
  src/components/Sidebar/Sidebar.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/create-folder-dialog.tsx
  src/screens/dialogs/index.ts
  src/services/files/list-file.service.ts
  src/services/folder/new-folder.service.ts
Labels: feature

#61 fix: Update nginx config
  Dockerfile
  config/default.nginx.conf
  nginx.conf
Labels: bug, cd

#60 feat: Rename files
  cypress/e2e/files/rename-files.cy.ts
  package.json
  src/components/Dialog.tsx
  src/components/FileElement/Dropdown.tsx
  src/components/FileElement/FileCard.tsx
  src/components/Sidebar/Sidebar.tsx
  src/context/FilesContext.tsx
  src/context/FilesDialogsContext.tsx
  src/context/index.ts
  src/hooks/index.ts
  src/hooks/useUserFiles.tsx
  src/main.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/create-folder-dialog.tsx
  src/screens/dialogs/index.ts
  src/screens/dialogs/rename-file-dialog.tsx
  src/services/files/rename-file.service.ts
Labels: feature

#62 feat: Get the users with whom a file is being shared
  src/components/Dialog.tsx
  src/components/FileElement/Dropdown.tsx
  src/context/FilesDialogsContext.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/access-file-dialog.tsx
  src/screens/dialogs/index.ts
  src/services/files/get-users-file.service.ts
Labels: feature

#63 release: v0.0.16
  CHANGELOG.md
  Dockerfile
  config/default.nginx.conf
  cypress/e2e/auth/login.cy.ts
  cypress/e2e/auth/register.cy.ts
  cypress/e2e/auth/tests-data.ts
  cypress/e2e/files/create-folder.cy.ts
  cypress/e2e/files/rename-files.cy.ts
  nginx.conf
  package.json
  pnpm-lock.yaml
  src/components/Dialog.tsx
  src/components/FileElement/Dropdown.tsx
  src/components/FileElement/FileCard.tsx
  src/components/Sidebar/Sidebar.tsx
  src/context/FilesContext.tsx
  src/context/FilesDialogsContext.tsx
  src/context/index.ts
  src/hooks/index.ts
  src/hooks/useUserFiles.tsx
  src/main.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/access-file-dialog.tsx
  src/screens/dialogs/create-folder-dialog.tsx
  src/screens/dialogs/index.ts
  src/screens/dialogs/rename-file-dialog.tsx
  src/services/files/get-users-file.service.ts
  src/services/files/list-file.service.ts
  src/services/files/rename-file.service.ts
  src/services/folder/new-folder.service.ts
Labels: cd

#64 feat: move a file
  cypress/e2e/files/move-file.cy.ts
  cypress/e2e/files/rename-files.cy.ts
  src/components/FileElement/Dropdown.tsx
  src/context/FilesContext.tsx
  src/context/FilesDialogsContext.tsx
  src/hooks/useUserFiles.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/index.ts
  src/screens/dialogs/move-file-dialog.tsx
  src/services/files/move-file.service.ts
Labels: feature

#69 release: v0.0.18
  CHANGELOG.md
  cypress/e2e/files/move-file.cy.ts
  cypress/e2e/files/rename-files.cy.ts
  package.json
  src/components/FileElement/Dropdown.tsx
  src/context/FilesContext.tsx
  src/context/FilesDialogsContext.tsx
  src/hooks/useUserFiles.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/index.ts
  src/screens/dialogs/move-file-dialog.tsx
  src/services/files/move-file.service.ts
Labels: cd

#66 feat: Delete files
  cypress/e2e/files/delete-files.cy.ts
  src/components/FileElement/Dropdown.tsx
  src/context/FilesContext.tsx
  src/context/FilesDialogsContext.tsx
  src/hooks/useUserFiles.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/delete-file-dialog.tsx
  src/screens/dialogs/index.ts
  src/services/files/delete-file.service.ts
Labels: feature

#56 feat: Update pasword modal
  cypress/e2e/update-password.cy.ts
  package.json
  pnpm-lock.yaml
  src/components/Button/ButtonSubmit.tsx
  src/components/Dialog.tsx
  src/components/Nav/Nav.tsx
  src/components/UpdatePassword/UpdatePasswordButton.tsx
  src/services/auth/updatepassword.service.ts
Labels: feature

#72 feat: Log out
  cypress/e2e/auth/logout.cy.ts
  cypress/e2e/update-password.cy.ts
  src/components/Nav/Nav.tsx
  src/components/ProfileButtons/LogOutButton.tsx
  src/components/ProfileButtons/UpdatePasswordButton.tsx
Labels: feature

#67 feat: un-share files
  src/screens/dialogs/access-file-dialog.tsx
  src/services/files/unshare-file.service.ts
Labels: feature

#73 release: v0.0.22
  CHANGELOG.md
  cypress/e2e/auth/logout.cy.ts
  cypress/e2e/files/delete-files.cy.ts
  cypress/e2e/update-password.cy.ts
  package.json
  pnpm-lock.yaml
  src/components/Button/ButtonSubmit.tsx
  src/components/Dialog.tsx
  src/components/FileElement/Dropdown.tsx
  src/components/Nav/Nav.tsx
  src/components/ProfileButtons/LogOutButton.tsx
  src/components/ProfileButtons/UpdatePasswordButton.tsx
  src/context/FilesContext.tsx
  src/context/FilesDialogsContext.tsx
  src/hooks/useUserFiles.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/access-file-dialog.tsx
  src/screens/dialogs/delete-file-dialog.tsx
  src/screens/dialogs/index.ts
  src/services/auth/updatepassword.service.ts
  src/services/files/delete-file.service.ts
  src/services/files/unshare-file.service.ts
Labels: cd

#65 feat: Upload files
  cypress/e2e/files/upload-files.cy.ts
  src/components/Sidebar/Sidebar.tsx
  src/context/FilesContext.tsx
  src/context/FilesDialogsContext.tsx
  src/hooks/useUserFiles.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/index.ts
  src/screens/dialogs/upload-file-dialog.tsx
  src/services/files/upload-file.service.ts
Labels: feature

#74 release: v0.0.23
  CHANGELOG.md
  cypress/e2e/files/share-file.cy.ts
  cypress/e2e/files/upload-files.cy.ts
  package.json
  src/components/Sidebar/Sidebar.tsx
  src/context/FilesContext.tsx
  src/context/FilesDialogsContext.tsx
  src/hooks/useUserFiles.tsx
  src/screens/FilePage.tsx
  src/screens/dialogs/access-file-dialog.tsx
  src/screens/dialogs/index.ts
  src/screens/dialogs/upload-file-dialog.tsx
  src/services/files/share-file.service.ts
  src/services/files/upload-file.service.ts
Labels: cd

#75 test: un-share
  cypress/e2e/files/share-file.cy.ts
  src/screens/dialogs/access-file-dialog.tsx
Labels: feature
