Repository hawks-atlanta/frontend-react, pull requests merged in 2023-09, with the labels that each got.

#13 feat: home page
  cypress/e2e/home.cy.ts
  package-lock.json
  package.json
  public/Logos/logo.png
  src/components/Button/Button.spec.cy.tsx
  src/components/Button/Button.tsx
  src/components/FeatureCard/FeatureCard.tsx
  src/components/Nav/Nav.tsx
  src/main.tsx
  src/screens/App.tsx
  src/screens/Login.tsx
  src/screens/Register.tsx
Labels: feature

#20 feat: Login UI
  src/components/Nav/Nav.tsx
  src/screens/Login.tsx
  src/screens/Register.tsx
Labels: feature

#22 style: login space
  src/screens/Login.tsx
Labels: bug

#24 cd: Release pipeline
  .github/workflows/release.yaml
  version.py
Labels: cd

#25 build: Fix release pipeline
  .dockerignore
Labels: bug, cd

#21 fix: responsive navbar
  cypress/e2e/home.cy.ts
  cypress/e2e/navbar.cy.ts
  src/components/Nav/Nav.tsx
  src/components/Nav/NavButton.tsx
Labels: bug, feature

#26 feat: Registration form, and validations
  cypress/e2e/register.cy.ts
  package-lock.json
  package.json
  src/screens/Register.tsx
Labels: feature
